### PR TITLE
initial support for indexing language strings

### PR DESCRIPTION
**Pull request by nvdk**
implements #57 , though  type should be specified as "type" instead of literal_type.

Example config:
```json
    {
      "type": "case",
      "on_path": "cases",
      "rdf_type": "http://mu.semte.ch/vocabularies/ext/Case",
      "properties": {
          "title": {
              "via": "http://purl.org/dc/terms/title",
              "type": "language-string"
          }
      }
    },
```

would allow searching on  the field `title.en` and `title.nl` if you have dutch and english titles. literals without a language are mapped onto a `default` field, so `title.default`

### CODE REVIEW

**Comment by MikiDi** [comment]
With current implementation, is there an option to search naïvely (without explicit language) on 1 specific property? From what I tested, `filter[title]=xyz` won't yield any results, while ideally, (for what that field is concerned) I'd want the same results as I get from `filter[_all]=xyz`, which is the object containing all languages. Does that sound like a reasonable request?

**Comment by nvdk** [comment]
as a workaround, you could add a separate field with no type, which will just index all strings into one field

**Comment by MikiDi** [comment]
The fallback might be even smarter from a api comsumer pov now you mention it, but I can confirm that `filter[title.*]=xyz` works too, which is nice :-)

**Comment by MikiDi** [comment]
Also: make sure to test this PR in conjunction with `latest` `mu-authorization`. [v0.6.0-beta.7](https://github.com/mu-semtech/mu-authorization/releases/tag/v0.6.0-beta.7) doesn't contain the necessary support for language tags in SPARQL.

**Comment by nvdk** [comment]
> There is still a pending issue with this PR: delta updates based on changes in `"language-string"`-properties don't work. The logic that determines if a delta is relevant doesn't take the language tags into account.

I've pushed a quick fix for this

**Pull request merged**
